kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: gopath
        path: /var/lib/gopath
      - name: gocache
        path: /var/lib/gocache
      - name: linter
        path: /var/lib/linter
    settings:
      output:
        name: model
      compress:
        enabled: false

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    when:
      event:
        - tag
    settings:
      output: $${CHANGELOG_TAG_OUTPUT}
      tag: $${DRONE_TAG}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      event:
        - tag
    environment:
      TOKEN:
        from_secret: token_github
    settings:
      release:
        tag: $${DRONE_TAG}
        token: $${TOKEN}
        body: expr:file("$${CHANGELOG_TAG_OUTPUT}")


volumes:
  - name: gopath
    host:
      path: /var/lib/cache/gopath
  - name: gocache
    host:
      path: /var/lib/cache/gocache
  - name: linter
    host:
      path: /var/lib/cache/linter
  - name: docker
    host:
      path: /var/lib/cache/docker
